language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "C+OjPUmEJ1s4DaE4YzYLYHey8EYjTrqnTeppW1e3gJt+tghH46d81WK8dd5hDeQX4jXbLtS/OIzc5rEF5vx5FSwDOQSFaYtAWHbklXJ9dV3XPT91mZOsvD7ZGa8OHtmStfRBmRWg/UHA7LZOM+dZ/aziQXl3ih33aVTb/AEOUlQK+a0bLpXfsWx2ele4uZ2iagj1rtILQERFFYKVcSr5xdZH+msZF1ad5VDkDj3LwnvOmyx/Wv1uJ98LGUmssZDRitin48NsTFqzzzC9s2QBO8TMal6rwNPy3sGfB0YwOEVfnSkOS0Vfu70DPWUzeK/946VyUAL/TWjsUOzb79tQgmPLsvnfOQYKYriwPKoyyi0LvoVo1cixxEuOkHeQ453e4fAFUy01uRS2pfycqpofjjf6dFDizW9uwPa+XgX807i0I//aWUlAUCXkpDUEbEBxug2HUgaBBFw9ToyOTeLX664WkoR/FLqmUq+oLQOJgaN4dDHPhicWesT9V5w6xZO17PpvOiY0wBJ7W/qkibTipacLdCG0p7Mx5+zAnLU+CD4MfJe92LTa7Ke4v+rSkNJ24PAOT2XHyq+lQtBf+/bc6nN/lb4W9f8w+KiUKMsTzMRpXEceNBN0/qU6CZmpNO+kRc0NwlWIGF3JbWlv3oHInTFAO0hVNxKdSlizurwGpMg="
app: beemie-the-chatbette
